### PR TITLE
SilverStripe 4 compatibility

### PR DESCRIPTION
**Pull request by kinglozzer**
Recommend creating a `1` branch before merging this.

Doesn’t touch anything to do with translatable (as that module hasn’t been updated yet)

### CODE REVIEW

**Comment by dhensby** [comment]
Green ticks, nice job!

**Comment by dhensby** [comment]
PHP 7 shouldn't be an allowed failure anymore

**Comment by kinglozzer** [comment]
> PHP 7 shouldn't be an allowed failure anymore

Good point, I’ve pushed a new commit for that. Also removed a 5.6 + MySQL from the build matrix, as it’s already run so is just duplicated.

**Comment by wilr** [comment]
Nice, thanks @kinglozzer for the work 👍

**Pull request merged**
