### PR TITLE
Use ClassName property instead of class

### PR DESCRIPTION
**Pull request by pavol-tk**
Property `class` does not exists. We should use `ClassName` instead.

### CODE REVIEW

**Comment by pavol-tk** [comment]
Please could you update package on packagist.org to 2.1.6?

**Comment by wilr** [comment]
Hi @pavol-tk, this should be automatically done when it next updates.

**Comment by pavol-tk** [comment]
There is a "This package is not auto-updated.".
image

**Comment by wilr** [comment]
@pavol-tk You're on the wrong packagist - https://packagist.org/packages/wilr/silverstripe-googlesitemaps#2.1.6

**Comment by pavol-tk** [comment]
Oh, thanks.
https://packagist.org/packages/silverstripe/googlesitemaps direct to 
https://github.com/silverstripe-labs/silverstripe-googlesitemaps redirect to
https://github.com/wilr/silverstripe-googlesitemaps

**Pull request merged**
