### PR TITLE
Handle cases such as 'Class.RelationName'

### PR DESCRIPTION
**Pull request by wilr**

### CODE REVIEW

**Comment by obj63mc** [comment]
When testing and further debugging I was able to get the following outputted when looking at what $type was - 

> array(3) { ["through"]=> string(35) "SilverStripe\CMS\Model\SiteTreeLink" ["from"]=> string(6) "Parent" ["to"]=> string(6) "Linked" }

**Comment by wilr** [comment]
@obj63mc Ah yep sorry just needed to move it after the through check.

**Comment by obj63mc** [comment]
With that last update, tested, all is working as expected now.

**Comment by wilr** [comment]
Thanks!

**Pull request merged**
